name: 'Frontend Continuous Deployment'
on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/frontend

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: caches npm
      id: restore-dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-${{ hashFiles('**/package-lock.json') }}
          npm-

    - name: Install dependencies
      run: npm ci

    - name: Run test
      run: CI=true npm test

  run-lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/frontend

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: caches npm
      id: restore-dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-${{ hashFiles('**/package-lock.json') }}
          npm-

    - name: Install dependencies
      run: npm ci

    - name: Run lint
      run: npm run lint
  
  build:
    needs: [run-test, run-lint]
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Restore dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: cd ./starter/frontend && npm install

      - name: Install prettier
        run: |
          cd ./starter/frontend 
          npm install prettier@2.8.8 --save-dev

      - name: Run lint check
        run: cd ./starter/frontend && npm run lint

      - name: Run test
        run: cd ./starter/frontend && npm run test
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1

      - name: Build Docker image
        run: |
          cd ./starter/frontend
          docker build -t frontend --build-arg=REACT_APP_MOVIE_API_URL=${{ vars.REACT_APP_MOVIE_API_URL }} .
      
      - name: Tag Docker Image
        run: |
          cd ./starter/frontend
          docker tag frontend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/frontend:latest

      - name: Push Docker image to ECR
        run: |
          cd ./starter/frontend
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
      
      - name: Kubeconfig Auth
        run: |
          aws eks update-kubeconfig --name cluster --region us-east-1
      
      - name: Deploy to Kubernetes
        run: |
          cd ./starter/frontend/k8s
          kustomize edit set image frontend= ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          kustomize build | kubectl apply -f -
